OPENEUROPA-2251: Allow adding languages into an ongoing translation.
ec-europa/oe-poetry-client pull request #83
Opened 2019-10-01 15:19 UTC by dxvargas

2020-02-24 14:40 UTC, imanoleguskiza requested changes

2020-02-24 14:40 UTC, imanoleguskiza commented on src/Messages/Components/ReturnAddress.php
> +            'expression' => 'this.getType() == "webService" or this.getPassword() == ""',
I don't understand this constraints, they don't seem to reflect what the message is saying.

2020-02-24 14:40 UTC, imanoleguskiza commented on src/Messages/Components/ReturnAddress.php
> +            'expression' => 'this.getType() == "webService" or this.getPath() == ""',
Same as the previous comment.

2020-02-25 14:42 UTC, upchuk commented on src/Messages/Components/ReturnAddress.php
> +            'expression' => 'this.getType() == "webService" or this.getPassword() == ""',
The constraint is there to allow other types with an empty password. Webservice always needs password.

2020-02-26 13:34 UTC, 22Alexandra approved these changes

2020-02-26 13:38 UTC, imanoleguskiza approved these changes

2020-02-26 13:41 UTC, merged